"""
Enkel flerspråkighet för Tunnelo. Nyckelbaserad ordbok, svenska + engelska.
Använd t(nyckel, lang) — saknas nyckeln returneras svenska (eller nyckeln själv).
"""

SPRAK = {"sv": "Svenska", "en": "English"}

TEXTER = {
    "sv": {
        "tagline": "privat VPN — koppla in dina enheter",
        "tillbaka": "Tillbaka",
        "logga_ut": "Logga ut",
        "om": "Om",
        # login
        "logga_in": "Logga in",
        "mailadress": "Mailadress",
        "skicka_kod": "Skicka inloggningslänk",
        "login_hjalp": "Vi mailar en inloggningslänk till din adress om den är registrerad.",
        "fel_ej_registrerad": "Adressen är inte registrerad i tvåstegsverifieringen.",
        # verify (länk-inloggning)
        "ange_kod": "Kolla din mejl",
        "verifiera_admin": "Verifiera administratör",
        "kod_mailad": "Vi skickade en inloggningslänk till",
        "lank_oppna_samma": "Öppna länken i den här webbläsaren — inloggningen sker här.",
        "lank_vantar": "Väntar på att du klickar länken…",
        "lank_fel_annan": "Länken måste öppnas i samma webbläsare där du angav din mejladress.",
        "lank_ogiltig": "Länken är ogiltig eller har gått ut.",
        "inloggningskod": "Inloggningskod",
        "annan_adress": "Annan adress",
        "fel_kod": "Fel eller utgången kod.",
        # setup
        "setup_undertitel": "första start — skapa administratör",
        "setup_titel": "Välkommen! Skapa administratör",
        "setup_hjalp": "Ange mailadressen som ska vara admin. Vi mailar en kod för att verifiera den. Admin kan sedan lägga till användare.",
        "admin_mail": "Admin-mailadress",
        "valj_sprak": "Välj språk",
        # home
        "ny_enhet": "Ny enhet",
        "enhet_namn_label": "Namn på enheten (t.ex. \"min-telefon\")",
        "skapa_qr": "Skapa & visa QR-kod",
        "enhet_hjalp": "Skapar en WireGuard-config du scannar med WireGuard-appen.",
        "enheter": "Enheter",
        "inga_enheter": "Inga enheter än — skapa din första ovan.",
        "verktyg": "Verktyg",
        "oppna_ssh": "Öppna SSH-terminal",
        "hantera_anvandare": "Hantera användare",
        "ssh_hjalp": "Öppna en terminal i webbläsaren mot servern eller en maskin på VPN-nätet — funkar även på mobilen.",
        "servern_nas": "Servern nås på",
        "trafik_genom": "trafik som går genom VPN",
        "ta_bort": "Ta bort",
        # users
        "lagg_till_anvandare": "Lägg till användare",
        "nat_label": "Nät/IP användaren når (CIDR, kommaseparerat)",
        "lagg_till": "Lägg till",
        "nat_hjalp": "Lämna tomt för standard (hela VPN-nätet). Exempel: 10.44.0.0/24, 192.168.1.10/32.",
        "anvandare": "Användare",
        "spara_nat": "Spara nät",
        "skyddad": "skyddad",
        # device
        "installera": "Installera",
        "scanna_mobil": "Det här är nyckeln för din mobil. Öppna WireGuard-appen, tryck + och välj \"Scanna QR-kod\" — då är telefonen ansluten. (På dator: använd flikarna nedan istället.)",
        "config_avancerat": "Config (avancerat)",
        "config_privat_varning": "Innehåller din privata nyckel — dela den inte.",
        "ladda_conf": "Ladda ner .conf",
        "install_skript_knapp": "Installationsskript",
        "maila_lank": "Maila installationslänken",
        "lank_mailad": "Installationslänken mailades till dig.",
        # terminal
        "ssh_anslutningar": "SSH-anslutningar",
        "ny_anslutning": "Ny anslutning",
        "anslut_nytt_fonster": "Anslut (nytt fönster)",
        "sparade_anslutningar": "Sparade anslutningar",
        "inga_sparade": "Inga sparade än — anslut ovan så frågar vi om du vill spara.",
        "favoriter": "Favoriter",
        "senaste_ssh": "Senaste inloggningar",
        "inga_favoriter": "Inga favoriter än — stjärnmärk en anslutning nedan.",
        "ingen_historik": "Ingen historik än — anslut ovan.",
        "host_anv": "Host / användare",
        "auto_start": "Starta automatiskt vid inloggning",
        "oppna_auto": "Öppna auto-anslutning",
        "magic_titel": "Logga in på Tunnelo",
        "magic_hjalp": "Klicka på knappen för att slutföra inloggningen.",
        "losen_ph": "Lösenord (sparas)",
        "vpn_enheter": "VPN-enheter",
        "meny": "Meny",
    },
    "en": {
        "tagline": "private VPN — connect your devices",
        "tillbaka": "Back",
        "logga_ut": "Log out",
        "om": "About",
        "logga_in": "Log in",
        "mailadress": "Email address",
        "skicka_kod": "Send login link",
        "login_hjalp": "We'll email a login link to your address if it's registered.",
        "fel_ej_registrerad": "This address is not registered for two-step verification.",
        "ange_kod": "Check your email",
        "verifiera_admin": "Verify administrator",
        "kod_mailad": "We sent a login link to",
        "lank_oppna_samma": "Open the link in this browser — you'll be logged in here.",
        "lank_vantar": "Waiting for you to click the link…",
        "lank_fel_annan": "The link must be opened in the same browser where you entered your email.",
        "lank_ogiltig": "The link is invalid or has expired.",
        "inloggningskod": "Login code",
        "annan_adress": "Different address",
        "fel_kod": "Wrong or expired code.",
        "setup_undertitel": "first run — create administrator",
        "setup_titel": "Welcome! Create administrator",
        "setup_hjalp": "Enter the email address that will be admin. We'll email a code to verify it. The admin can then add users.",
        "admin_mail": "Admin email address",
        "valj_sprak": "Choose language",
        "ny_enhet": "New device",
        "enhet_namn_label": "Device name (e.g. \"my-phone\")",
        "skapa_qr": "Create & show QR code",
        "enhet_hjalp": "Creates a WireGuard config you scan with the WireGuard app.",
        "enheter": "Devices",
        "inga_enheter": "No devices yet — create your first one above.",
        "verktyg": "Tools",
        "oppna_ssh": "Open SSH terminal",
        "hantera_anvandare": "Manage users",
        "ssh_hjalp": "Open a terminal in the browser to the server or a machine on the VPN — works on mobile too.",
        "servern_nas": "Server reached at",
        "trafik_genom": "traffic routed through the VPN",
        "ta_bort": "Remove",
        "lagg_till_anvandare": "Add user",
        "nat_label": "Networks/IPs the user can reach (CIDR, comma-separated)",
        "lagg_till": "Add",
        "nat_hjalp": "Leave empty for default (the whole VPN network). Example: 10.44.0.0/24, 192.168.1.10/32.",
        "anvandare": "Users",
        "spara_nat": "Save networks",
        "skyddad": "protected",
        "installera": "Install",
        "scanna_mobil": "This is the key for your phone. Open the WireGuard app, tap + and choose \"Scan QR code\" — your phone is then connected. (On a computer: use the tabs below instead.)",
        "config_avancerat": "Config (advanced)",
        "config_privat_varning": "Contains your private key — don't share it.",
        "ladda_conf": "Download .conf",
        "install_skript_knapp": "Install script",
        "maila_lank": "Email the install link",
        "lank_mailad": "The install link was emailed to you.",
        "ssh_anslutningar": "SSH connections",
        "ny_anslutning": "New connection",
        "anslut_nytt_fonster": "Connect (new window)",
        "sparade_anslutningar": "Saved connections",
        "inga_sparade": "None saved yet — connect above and we'll ask if you want to save it.",
        "favoriter": "Favorites",
        "senaste_ssh": "Recent logins",
        "inga_favoriter": "No favorites yet — star a connection below.",
        "ingen_historik": "No history yet — connect above.",
        "host_anv": "Host / user",
        "auto_start": "Start automatically at login",
        "oppna_auto": "Open auto connection",
        "magic_titel": "Log in to Tunnelo",
        "magic_hjalp": "Click the button to complete your login.",
        "losen_ph": "Password (saved)",
        "vpn_enheter": "VPN devices",
        "meny": "Menu",
    },
}


def t(nyckel, lang="sv"):
    sv = TEXTER["sv"]
    return TEXTER.get(lang, sv).get(nyckel) or sv.get(nyckel, nyckel)
